---
- name: Setup Master
  hosts: all 
  remote_user: root
  tasks:
    - name: Set Hostname
      command:
        cmd: "hostnamectl set-hostname master"
    - name: Create admin group
      group:
        name: admin
        state: present
    - name: Create user
      user:
        name: "{{ item.name }}"
        groups: admin
        shell: /bin/zsh
      with_items: "{{ users }}"
    - name: SSH Pub Key
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      with_items: "{{ users }}"
    - name: Allow passwordless sudo
      lineinfile:
        dest: "/etc/sudoers"
        state: "present"
        regexp: "^%admin"
        line: "%admin ALL=(ALL) NOPASSWD: ALL"
    - name: Update Apt
      apt:
        update_cache: true
    - name: Install Zsh
      apt:
        name: "zsh"
    - name: Install Git
      apt:
        name: "git"
    - name: Install Oh My Zsh
      shell:
        warn: false
        creates: "/home/{{ item.name }}/.oh-my-zsh"
        cmd: "runuser -l {{ item.name }} -c 'curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh'"
      with_items: "{{ users }}"
    - name: Copy .zshrc
      copy:
        dest: "/home/{{ item.name }}/.zshrc"
        mode: '1644'
        src: "./configs/.zshrc"
      with_items: "{{ users }}"
      
- name: Setup Packages Master
  hosts: all 
  remote_user: root
  tasks:
    - name: Update Apt
      apt:
        update_cache: true
    - name: Install Packages
      apt:
        name: "{{ item.name }}"
      with_items: "{{ packages }}"
    - name: Install NVM
      shell:
        warn: false
        creates: "/home/{{ item.name }}/.nvm"
        cmd: "runuser -l {{ item.name }} -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | zsh'"
      with_items: "{{ users }}"